name: CI-Docker

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3

    - name: Extract DOCKER_TAG using tag name
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        echo "DOCKER_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
    
    - name: Use default DOCKER_TAG
      if: startsWith(github.ref, 'refs/tags/') != true
      run: |
        echo "DOCKER_TAG=latest" >> $GITHUB_ENV
      
    - name: Login to Github registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        
    - name: Set lowercase repository name
      run: |
        echo "REPOSITORY_LC=${REPOSITORY,,}" >>${GITHUB_ENV}
      env:
        REPOSITORY: '${{ github.repository }}'
    
    - uses: docker/build-push-action@v3
      with:
        push: ${{ github.event_name != 'pull_request' }}
        tags: ghcr.io/${{ env.REPOSITORY_LC }}:${{ env.DOCKER_TAG }} 
        build-args: |
          SWIFLINT_DOCKER_IMAGE=ghcr.io/realm/swiftlint:0.46.5
          CARTON_TAG=0.17.0
          SWIFT_DOCKER_IMAGE=swift:5.7.0-focal
          SWIFT_TAG=swift-wasm-5.7.3-RELEASE
          SWIFT_FORMAT_TAG=0.50700.0
          NODE_VERSION=16.x
          OPEN_JDK_VERSION=11
          CYPRESS_VERSION=12.3.0
          CHROME_VERSION=101.0.4951.54
          CHROME_DRIVER_VERSION=101.0.4951.41
          FIREFOX_VERSION=99.0.1
          SYMBOLICATOR_VERSION=0.5.0
